{% set name = "marshmallow-jsonapi" %}
{% set version = "0.16.0" %}
{% set sha256 = "a0691dbd772bd14cb011ccb557ce0e4714ed602dae4f900c64ac579052641f79" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - marshmallow >=2.3.0

test:
  imports:
    - marshmallow_jsonapi

about:
  home: http://github.com/marshmallow-code/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'JSON API 1.0 formatting with marshmallow'

  description: |
      marshmallow-jsonapi provides a simple way to produce JSON API-compliant data in any Python web framework.

  doc_url: http://{{ name }}.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/{{ name }}

extra:
  recipe-maintainers:
    - sodre
