travis:
  secure:
    BINSTAR_TOKEN: KOts4mb6uIxwi+s+yICAxkcQM/p11lYaCQezkUBtXkMOhLWsDlmVlNTgICqclJ1l3CZmhUT6FjMOUnd/d2ljjWFF8mSwv9tpQjb1k1cAxmkwpgybNubsCJgHerjulWP0bKhRy253pwuLQm2nDlBomlbcO71t8KgJVY+9o8jM2519AgERSj35bgEynQ90fs6qBlEGGc6/zrKkGvE/Lyk4Ifc/yr5m4xEcGhTJCAMdEWCg4CexLsKcPJs7BWNPfBPEnwW3ZoLCUKnh3FwN4Olm6xQpon0IKXAIl14/WyaaSH1suau/ALb9RriEKxx1zXooexX4v6QqhvAqwzh4O4NhcMT0mh8pOSjw6E5NEwnQqdfNzOQeOXqIUlWQIS7DePT0Wt7WC4cFM3haetQbnNuhu48St9hD4yaQiZ+NyLMq2qKqrrvj0z6XYHG+Blla4gTd7ftAe05kbUEvUHqDLUD63uuyk70i9MndbRotOegJHnUZP8qn2pIWQbUI2JYvC+S4nqnWtDzmWRAdFtRruyAObl7ujwlPhA8S87epbb2VKxi7MvjtR3fF7uJGwIdzEn66EcExknZpH2g5A9R+E5cLZa2EhWfdxy2De3IhMWrKRyQOp4K7R+76S7BouWYV9PT3W6VrV82euKXkjjVhuC5qhiy+Zni8b59SH8ylsAqim1s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
