travis:
  secure:
    BINSTAR_TOKEN: Ztt/4RAWfgpc8fFkjLsp9PJTmhFSB8XnQOjJTz2Zm2v+wLNLtZneE5F2KjIfcNP+8eOk+8tZMsMiCZzXk6dFmYW+zQpZ7RVGi/bsnNqBA40ucVDZk1LST1/nLt/LQc+rc48P3MXY72kI7n5aV3Xi0yN8fDTxPzsMEvQ5wa6YJLr1blJBjw2k38IIKYkRCUSxTkAsXqNXW4YKv9KcMlML8wFTSIdCqW0o1ivhB4FHGXlmIB0vtTEwsWle7BlssXSwcF1AJ2skzp3zAh0YfoVZrG2NHeSzLurgJEiEMMGvEZ65QfsY3jeclGFAzcKw/P/Hl2HMgLAskN9Mk4uw2hNfB8JIhtuwQGK7x03x5rsb7z3MFEwLWB0hhw4ghIg8o72Wx3etJ8YQXXHpZoeJWsFIIAdo6wHFlirWpJy0gAoOJn/l/5Rib7+CkL7uwIvZTlacIKA6qLHWptexS1CdiA2qGPGHtOUY/jfmm5zcD4gNeryqficHVSIofod2IXWXvZPt2Z6nOBHgcWxe2wD4TX+HBD/mjLhkKw3NZFJ4oW1nthzvP1ElDdVY1fAjdnM1MEfZVDdgeY4goN7lbcqpA5/EElkiy5RIKtlGNgkfAVXc6k/urXs8iSLPqC5HI44gCmc3uI8afR89bY5bHiHXBuqtIV6GSoxCC6Mi7U1JzKFLjXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
