travis:
  secure:
    BINSTAR_TOKEN: ALcvm1IdU2TokzmIQuLowmKlsv99pKFh8zWplqAYz+U2rDfgUG2AE7LZ3BBVOAOT4ncnJOSpks8EyM/mf38rnomvaQkp+eXxNu9JFV+NfTR4RJ5sINqx0BhQIqnoyWRJZLFH//TqznJ89j8yopgNZPh5T4fflaqyRq7qOk5xae2mLrUvYn1fmBxs3sJvbpLRDFU1W5ortURGBFbj92M7R90mLZaGICgRcQyMs8IHi10aXDnmqnvyDSKqU92d/4GSKB94IhkUE1wA6LGM7+EWkK6VDis5OFTOO81c4+wFa7+XoUCQAgj4JwxXnb743B+rCzYGD21jsPlHHRNS9KAfbKuiKv3+YKznUZYfZrEWONAtsCBZY03Io56hwI5jO4Y0LBln4iSUzQZz4AkaDekQyoFe2J9nVcc4IM/ufyw270CAH2kkAY3O/OYkqoavBKuoTJUubuNfqh4hzrCqLNUinb5BhlfsJaGkQp0DgmGLuuwfnLPVs/+1P1mMvcGBt5u7TKoY2swngB1KDHTBdarO+AUPLlEmfns/fVxEuRXBSqAb8PPToC4lahBgbaeKpTRRcr1I3lVcI047pPwEKT/5xMl+sCba53Z7/Z5dVP/eJWGM13TkVKEni28Ohb9NFH470jlULoq0hYMHxlnGQV9KVDJmYG/3YqPLZ0g08QFQ36c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
